import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {api} from './services/api'; import './styles.css'; import type {User} from './types';
function App(){const [user,setUser]=useState<User|null>(null); const [mode,setMode]=useState<'login'|'register'>('login'); const [profile,setProfile]=useState(false); const [msg,setMsg]=useState(''); const [form,setForm]=useState({name:'',email:'',password:'',currentPassword:'',newPassword:''});
useEffect(()=>{if(localStorage.getItem('stockpass_token')) api.get('/auth/profile').then(r=>setUser(r.data)).catch(()=>localStorage.removeItem('stockpass_token'));},[]);
async function submit(e:React.FormEvent){e.preventDefault();setMsg('');try{if(mode==='login'){const r=await api.post('/auth/login',{email:form.email,password:form.password});localStorage.setItem('stockpass_token',r.data.token);setUser(r.data.user);}else{await api.post('/auth/register',{name:form.name,email:form.email,password:form.password});setMsg('Cadastro realizado. Agora faça login.');setMode('login');}}catch(err:any){setMsg(err?.response?.data?.message||'Não foi possível concluir a operação.');}}
async function changePassword(e:React.FormEvent){e.preventDefault();try{await api.put('/auth/password',{currentPassword:form.currentPassword,newPassword:form.newPassword});setMsg('Senha alterada com sucesso.');setForm({...form,currentPassword:'',newPassword:''});}catch(err:any){setMsg(err?.response?.data?.message||'Erro ao alterar senha.');}}
function logout(){localStorage.removeItem('stockpass_token');setUser(null);setProfile(false);}
if(!user)return <main className="page"><section className="card auth"><h1>StockPass</h1><p className="muted">Sistema de Controle de Estoque</p><h2>{mode==='login'?'Entrar':'Criar conta'}</h2><form onSubmit={submit}>{mode==='register'&&<input placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input type="email" placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Senha" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={6} required/><button>{mode==='login'?'Entrar':'Cadastrar'}</button></form>{msg&&<p className="message">{msg}</p>}<button className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setMsg('')}}>{mode==='login'?'Ainda não tenho cadastro':'Já tenho uma conta'}</button></section></main>;
return <main className="page"><header><div><h1>StockPass</h1><p className="muted">Olá, {user.name}!</p></div><button className="secondary" onClick={()=>setProfile(!profile)}>{profile?'Voltar':'Meu perfil'}</button><button className="danger" onClick={logout}>Sair</button></header>{profile?<section className="grid"><div className="card"><h2>Perfil</h2><p><b>Nome:</b> {user.name}</p><p><b>E-mail:</b> {user.email}</p><p><b>Perfil:</b> {user.role}</p></div><div className="card"><h2>Trocar senha</h2><form onSubmit={changePassword}><input type="password" placeholder="Senha atual" value={form.currentPassword} onChange={e=>setForm({...form,currentPassword:e.target.value})} required/><input type="password" placeholder="Nova senha" value={form.newPassword} onChange={e=>setForm({...form,newPassword:e.target.value})} minLength={6} required/><button>Alterar senha</button></form>{msg&&<p className="message">{msg}</p>}</div></section>:<section className="card"><h2>Dashboard</h2><p>Login realizado com sucesso.</p><div className="hello">Hello World — StockPass</div><p className="muted">A base de controle de acesso está pronta para receber as próximas rotinas de produtos, categorias, fornecedores e movimentações.</p></section>}</main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
